# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1deeb924f7dcbd1120a616aa0439c63b5f6e66111aa4272f95e62721db86196281c87946f2698afa4790f7d4ddf5fe40b253fdaa243fcf4e03377c15cfa4ea73

test:
  secret_key_base: 2c0c81a58ad8dfeeaf33fa73ade531ab414f77b6872dfcd5b29c77be06d2424b2ee4215dc3523c88b543b014996a6bad301cdc0ffe9941cc7a73d0198b95ab2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
